[package]
name = "fs-more"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["fs-more-test-harness"]

[dependencies]
thiserror = "1.0.48"

[dev-dependencies]
assert_fs = "1.0.13"
assert_matches = "1.5.0"
fs-more-test-harness = { path = "./fs-more-test-harness" }
